### ISSUE TITLE
Add rate limiting at the application level, not just SSH

### ISSUE THREAD

**Issue by robinje** [darkrelics/eidolon-engine#493]
## Description
Currently, rate limiting is only implemented at the SSH connection level. This is insufficient as a single connection can execute unlimited commands, potentially overwhelming the server. Application-level rate limiting is needed to ensure fair resource usage and prevent abuse.

## Current State
- SSH connections are rate limited
- No limits on command execution frequency
- No limits on resource-intensive operations
- Single player can monopolize server resources
- No differentiation between command types

## Proposed Solution
Implement multi-tier rate limiting at the application level:

### Rate Limiting Tiers
1. **Global Rate Limits**
   - Overall server command processing rate
   - Prevents server overload

2. **Per-Player Rate Limits**
   - Commands per minute/hour
   - Different limits for different command types
   - Adaptive limits based on player behavior

3. **Command-Specific Limits**
   - Movement commands: 60/minute
   - Combat commands: 120/minute
   - Administrative commands: 10/minute
   - Database-heavy commands: 20/minute

### Implementation Strategy
```go
type RateLimiter interface {
    Allow(playerID uuid.UUID, commandType string) bool
    Reset(playerID uuid.UUID)
    SetLimit(commandType string, limit int, window time.Duration)
    GetMetrics() RateLimitMetrics
}
```

## Acceptance Criteria
- [ ] Design flexible rate limiting system
- [ ] Implement token bucket algorithm
- [ ] Add per-player rate limits
- [ ] Add per-command-type limits
- [ ] Implement rate limit headers in responses
- [ ] Add metrics and monitoring
- [ ] Graceful handling when limits exceeded
- [ ] Configuration via YAML
- [ ] Unit and integration tests
- [ ] Documentation for administrators

## Configuration Example
```yaml
rate_limits:
  global:
    commands_per_second: 1000
  per_player:
    default:
      commands_per_minute: 60
      commands_per_hour: 2000
    premium:
      commands_per_minute: 120
      commands_per_hour: 5000
  command_types:
    movement:
      per_minute: 60
    combat:
      per_minute: 120
    admin:
      per_minute: 10
    database_intensive:
      per_minute: 20
```

## Benefits
- **Stability**: Prevents server overload
- **Fairness**: Ensures equal access for all players
- **Security**: Mitigates DoS attacks
- **Performance**: Predictable server load
- **Flexibility**: Configurable limits per command type

## Monitoring
- CloudWatch metrics for rate limit hits
- Alerts for unusual patterns
- Dashboard showing current usage vs limits
