### ISSUE TITLE
Create EC2 AMI Deployment Pipeline using CodeBuild and Packer

### ISSUE THREAD

**Issue by robinje** [darkrelics/eidolon-engine#509]
## Overview
Implement an automated EC2 instance deployment pipeline using AWS CodeBuild and Packer to create custom AMIs for the Eidolon Engine server. 

### 1. Packer Template
Create a Packer template that:
- Starts from Amazon Linux 2023 or Ubuntu 22.04 base AMI
- Installs required dependencies (Go runtime, Git, etc.)
- Copies the compiled Eidolon Engine binary
- Configures systemd service for automatic startup
- Sets up CloudWatch agent for logs/metrics
- Configures SSH keys for emergency access
- Implements security hardening (firewall rules, etc.)

### 2. CodeBuild Project for AMI Building
- Trigger on successful server build completion
- Run Packer to create new AMI
- Tag AMI with version info (git commit, timestamp, build number)
- Validate AMI creation
- Update AMI ID in parameter store or outputs

#### `packer/eidolon-server.pkr.hcl`
```hcl
packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "ami_name_prefix" {
  type    = string
  default = "eidolon-engine"
}

variable "build_version" {
  type    = string
  default = "dev"
}

variable "binary_path" {
  type    = string
  default = "../server/eidolon-engine"
}

source "amazon-ebs" "eidolon" {
  ami_name      = "${var.ami_name_prefix}-${var.build_version}-{{timestamp}}"
  instance_type = "t3.micro"
  region        = "us-east-1"
  
  source_ami_filter {
    filters = {
      name                = "al2023-ami-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["amazon"]
  }
  
  ssh_username = "ec2-user"
  
  tags = {
    Name        = "Eidolon Engine Server"
    Version     = "${var.build_version}"
    BuildTime   = "{{timestamp}}"
    Application = "eidolon-engine"
  }
}

build {
  sources = ["source.amazon-ebs.eidolon"]
  
  # Copy server binary
  provisioner "file" {
    source      = var.binary_path
    destination = "/tmp/eidolon-engine"
  }
  
  # Copy systemd service file
  provisioner "file" {
    source      = "../deployment/eidolon.service"
    destination = "/tmp/eidolon.service"
  }
  
  # Setup script
  provisioner "shell" {
    script = "../deployment/setup-server.sh"
  }
}
```

#### `deployment/eidolon.service`
```ini
[Unit]
Description=Eidolon Engine Game Server
After=network.target

[Service]
Type=simple
User=eidolon
Group=eidolon
WorkingDirectory=/opt/eidolon
ExecStart=/opt/eidolon/eidolon-engine
Restart=always
RestartSec=10

# Security
NoNewPrivileges=true
PrivateTmp=true

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=eidolon

[Install]
WantedBy=multi-user.target
```

#### `deployment/setup-server.sh`
```bash
#\!/bin/bash
set -e

# Create eidolon user
sudo useradd -r -s /bin/false eidolon || true

# Create directories
sudo mkdir -p /opt/eidolon/data
sudo mkdir -p /etc/eidolon

# Install binary
sudo mv /tmp/eidolon-engine /opt/eidolon/
sudo chmod +x /opt/eidolon/eidolon-engine

# Install systemd service
sudo mv /tmp/eidolon.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable eidolon.service

# Set permissions
sudo chown -R eidolon:eidolon /opt/eidolon

# Install CloudWatch agent
wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
sudo rpm -U ./amazon-cloudwatch-agent.rpm
rm ./amazon-cloudwatch-agent.rpm

# Configure firewall
sudo firewall-cmd --permanent --add-port=9050/tcp
sudo firewall-cmd --reload
```

#### `buildspec/ami-build.yml`
```yaml
version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Packer...
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install packer
      
  build:
    commands:
      - echo Building AMI with Packer...
      - cd packer
      - |
        packer build \
          -var "build_version=${CODEBUILD_RESOLVED_SOURCE_VERSION}" \
          -var "binary_path=${CODEBUILD_SRC_DIR_BuildArtifact}/eidolon-engine" \
          eidolon-server.pkr.hcl
      
  post_build:
    commands:
      - echo AMI build completed
      - |
        # Extract AMI ID from Packer output and store in parameter store
        AMI_ID=$(packer build -machine-readable eidolon-server.pkr.hcl | awk -F, '$3 == "artifact" && $5 == "id" {print $6}' | cut -d: -f2)
        aws ssm put-parameter --name "/eidolon/ami/latest" --value "$AMI_ID" --type String --overwrite

artifacts:
  files:
    - 'packer-manifest.json'
```

### 5. CloudFormation Updates

Add CodeBuild project for AMI building:

```yaml
AMIBuildProject:
  Type: AWS::CodeBuild::Project
  Properties:
    Name: eidolon-ami-build
    ServiceRole: \!GetAtt CodeBuildRole.Arn
    Artifacts:
      Type: CODEPIPELINE
    Environment:
      Type: LINUX_CONTAINER
      ComputeType: BUILD_GENERAL1_SMALL
      Image: aws/codebuild/standard:7.0
      PrivilegedMode: true
    Source:
      Type: CODEPIPELINE
      BuildSpec: buildspec/ami-build.yml
```

### 6. Benefits
- **Immutable Infrastructure**: Each deployment is a new AMI
- **Version Tracking**: AMIs tagged with git commit and timestamp
- **Rollback Capability**: Previous AMIs retained for quick rollback
- **Security**: Consistent security hardening applied
- **Automation**: No manual server configuration needed

### 7. Future Enhancements
- Auto-scaling group integration
- Blue/green deployments
- Automatic instance replacement
- Multi-region AMI copying
- Integration with AWS Systems Manager

## Dependencies
- Requires server build artifacts from CodeBuild
- Needs appropriate IAM permissions for Packer
- Should integrate with existing CloudFormation stacks

## Testing
- Validate AMI boots correctly
- Verify systemd service starts
- Check CloudWatch integration
- Test SSH access
- Validate game server connectivity
