### ISSUE TITLE
Set Up Test User Management for Automated Testing

### ISSUE THREAD

**Issue by robinje** [darkrelics/eidolon-engine#513]
## Overview
To support the smoke test script and future automated testing, we need a system for managing test user accounts in Cognito and test data in DynamoDB. This ensures tests can run reliably without manual account creation.

### 1. Test Account Management
- Create and manage test user accounts in Cognito
- Generate predictable but secure passwords
- Handle account cleanup after tests
- Support multiple test accounts for concurrent testing

### 2. Test Data Management
- Create test characters automatically
- Set up test rooms and items
- Ensure consistent test environment
- Clean up test data after runs

### 3. Environment Isolation
- Separate test accounts from production
- Use test-specific prefixes or attributes
- Prevent test data from affecting real users

#### `tests/setup_test_accounts.py`
```python
#\!/usr/bin/env python3
"""
Set up test accounts for Eidolon Engine automated testing
"""

import boto3
import json
import sys
from datetime import datetime
import uuid

class TestAccountManager:
    def __init__(self, user_pool_id, region='us-east-1'):
        self.cognito = boto3.client('cognito-idp', region_name=region)
        self.dynamodb = boto3.resource('dynamodb', region_name=region)
        self.user_pool_id = user_pool_id
        
    def create_test_user(self, username, password, attributes=None):
        """Create a test user in Cognito"""
        try:
            # Create user
            response = self.cognito.admin_create_user(
                UserPoolId=self.user_pool_id,
                Username=username,
                UserAttributes=[
                    {'Name': 'email', 'Value': username},
                    {'Name': 'custom:test_account', 'Value': 'true'},
                    {'Name': 'custom:created_at', 'Value': datetime.utcnow().isoformat()},
                ] + (attributes or []),
                TemporaryPassword=password,
                MessageAction='SUPPRESS'  # Don't send welcome email
            )
            
            # Set permanent password
            self.cognito.admin_set_user_password(
                UserPoolId=self.user_pool_id,
                Username=username,
                Password=password,
                Permanent=True
            )
            
            print(f"Created test user: {username}")
            return response['User']
            
        except self.cognito.exceptions.UsernameExistsException:
            print(f"Test user already exists: {username}")
            return self.get_user(username)
    
    def create_test_character(self, player_email, character_name):
        """Create a test character in DynamoDB"""
        characters_table = self.dynamodb.Table('characters')
        players_table = self.dynamodb.Table('players')
        
        # Create player record if needed
        player_id = str(uuid.uuid4())
        players_table.put_item(
            Item={
                'PlayerID': player_id,
                'Email': player_email,
                'CharacterList': {character_name: str(uuid.uuid4())},
                'SeenMotD': [],
                'TestAccount': True
            },
            ConditionExpression='attribute_not_exists(PlayerID)'
        )
        
        # Create character
        character_id = str(uuid.uuid4())
        characters_table.put_item(
            Item={
                'CharacterID': character_id,
                'PlayerID': player_email,
                'CharacterName': character_name,
                'Attributes': {
                    'strength': 10.0,
                    'dexterity': 10.0,
                    'intelligence': 10.0
                },
                'Abilities': {},
                'Health': 10.0,
                'Essence': 3.0,
                'RoomID': 'test_room_1',
                'Inventory': {},
                'TestCharacter': True
            }
        )
        
        print(f"Created test character: {character_name} for {player_email}")
        return character_id
    
    def cleanup_test_accounts(self, older_than_hours=24):
        """Remove old test accounts"""
        # List users with test_account attribute
        paginator = self.cognito.get_paginator('list_users')
        
        for page in paginator.paginate(
            UserPoolId=self.user_pool_id,
            Filter='custom:test_account = "true"'
        ):
            for user in page['Users']:
                # Check age
                created_at = None
                for attr in user['Attributes']:
                    if attr['Name'] == 'custom:created_at':
                        created_at = datetime.fromisoformat(attr['Value'])
                        break
                
                if created_at:
                    age_hours = (datetime.utcnow() - created_at).total_seconds() / 3600
                    if age_hours > older_than_hours:
                        self.delete_test_user(user['Username'])
    
    def delete_test_user(self, username):
        """Delete a test user and associated data"""
        try:
            # Delete from Cognito
            self.cognito.admin_delete_user(
                UserPoolId=self.user_pool_id,
                Username=username
            )
            
            # Delete from DynamoDB
            # ... cleanup character and player data ...
            
            print(f"Deleted test user: {username}")
            
        except Exception as e:
            print(f"Error deleting test user {username}: {e}")

def main():
    # Load configuration
    with open('../server/config.yml', 'r') as f:
        config = json.load(f)
    
    user_pool_id = config['Cognito']['UserPoolId']
    
    # Create test account manager
    manager = TestAccountManager(user_pool_id)
    
    # Standard test accounts
    test_accounts = [
        {
            'username': 'smoketest@eidolon.test',
            'password': 'SmokeTest123\!',
            'character': 'SmokeTestChar'
        },
        {
            'username': 'integration1@eidolon.test',
            'password': 'Integration123\!',
            'character': 'IntTestChar1'
        },
        {
            'username': 'integration2@eidolon.test',
            'password': 'Integration123\!',
            'character': 'IntTestChar2'
        },
        {
            'username': 'loadtest@eidolon.test',
            'password': 'LoadTest123\!',
            'character': 'LoadTestChar'
        }
    ]
    
    # Create accounts
    for account in test_accounts:
        user = manager.create_test_user(
            account['username'],
            account['password']
        )
        
        if user:
            manager.create_test_character(
                account['username'],
                account['character']
            )
    
    # Cleanup old test accounts
    if '--cleanup' in sys.argv:
        print("\nCleaning up old test accounts...")
        manager.cleanup_test_accounts(older_than_hours=24)
    
    print("\nTest account setup complete\!")

if __name__ == '__main__':
    main()
```

#### `tests/test_config.yml`
```yaml
# Test environment configuration
test_accounts:
  smoke_test:
    username: smoketest@eidolon.test
    password: SmokeTest123\!
    character_name: SmokeTestChar
    
  integration_test_1:
    username: integration1@eidolon.test
    password: Integration123\!
    character_name: IntTestChar1
    
  integration_test_2:
    username: integration2@eidolon.test
    password: Integration123\!
    character_name: IntTestChar2
    
  load_test:
    username: loadtest@eidolon.test
    password: LoadTest123\!
    character_name: LoadTestChar

test_rooms:
  - room_id: test_room_1
    name: Test Starting Room
    description: A simple room for testing
    exits:
      north: test_room_2
      
  - room_id: test_room_2
    name: Test Second Room
    description: Another test room
    exits:
      south: test_room_1

test_items:
  - item_id: test_sword_1
    name: Test Sword
    description: A basic test weapon
    room_id: test_room_1
```

#### `.github/workflows/test.yml`
```yaml
name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Python dependencies
      run: |
        pip install boto3 pyyaml paramiko
    
    - name: Set up test accounts
      run: |
        cd tests
        python setup_test_accounts.py
    
    - name: Build server
      run: make build
    
    - name: Run smoke test
      run: make smoke-test
    
    - name: Cleanup test accounts
      if: always()
      run: |
        cd tests
        python setup_test_accounts.py --cleanup
```

#### `.env.test`
```bash
# Test environment variables
EIDOLON_TEST_USER_POOL_ID=us-east-1_xxxxxxxxx
EIDOLON_TEST_REGION=us-east-1
EIDOLON_TEST_SERVER_HOST=localhost
EIDOLON_TEST_SERVER_PORT=9050

# Test account credentials (for local testing only)
EIDOLON_TEST_USERNAME=smoketest@eidolon.test
EIDOLON_TEST_PASSWORD=SmokeTest123\!
```

## Security Considerations

1. **Test Account Isolation**:
   - Use custom Cognito attributes to mark test accounts
   - Implement server-side filtering to hide test accounts
   - Use `.test` email domain for clear identification

2. **Credential Management**:
   - Store test passwords in secure environment variables
   - Rotate test passwords regularly
   - Never use production-like passwords

3. **Data Cleanup**:
   - Automatic cleanup of old test data
   - Prevent test data accumulation
   - Clear audit trail of test operations

## Benefits

1. **Automated Testing**: No manual account setup required
2. **Consistent Environment**: Same test data every run  
3. **Parallel Testing**: Multiple test accounts for concurrent tests
4. **Easy Cleanup**: Remove test data with single command
5. **Security**: Clear separation from production data

## Future Enhancements

1. **Test Data Fixtures**:
   - Pre-defined room layouts
   - Complex item hierarchies
   - NPC test data

2. **Performance Testing**:
   - Generate hundreds of test accounts
   - Simulate realistic player populations
   - Load testing scenarios

3. **Test Isolation**:
   - Separate test database tables
   - Test-specific server instances
   - Docker-based test environments

## Dependencies

- AWS SDK (boto3)
- Cognito user pool with custom attributes
- DynamoDB tables
- Python 3.12+
